"use client";

import { Check, Clock, ChevronDown } from "lucide-react";

const pillars = [
  {
    icon: Check,
    title: "Zero Manual Documentation",
    glyph: "✔",
    description:
      "No handwritten or manually typed compliance records — every GMP document generated by AI in real time.",
  },
  {
    icon: Clock,
    title: "Zero Compliance Gaps",
    glyph: "⌚",
    description:
      "Every record validated against live regulatory guidelines before reaching the officer. No exceptions.",
  },
  {
    icon: ChevronDown,
    title: "24/7 Audit Readiness",
    glyph: "▼",
    description:
      "Always inspection-ready — AI audit agent monitors plant operations round the clock.",
  },
];

export default function VisionPillars() {
  return (
    <section
      id="pillars"
      className="relative py-24 px-4 bg-gradient-to-b from-[#f0fdfd] via-white to-[#f9fefe] overflow-hidden"
    >
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[min(90%,720px)] h-32 bg-teal-200/40 blur-3xl rounded-full pointer-events-none" />

      <div className="relative max-w-7xl mx-auto z-10">
        <div className="text-center mb-16" data-aos="fade-up">
          <p className="text-sm font-semibold tracking-widest text-teal-600 uppercase mb-3">
            How we deliver the vision
          </p>
          <h2 className="text-3xl md:text-4xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-teal-600 via-cyan-600 to-sky-600">
            Three pillars
          </h2>
          <div className="mt-3 h-1 w-20 bg-teal-400 mx-auto rounded-full" />
        </div>

        <div className="grid md:grid-cols-3 gap-8 lg:gap-10">
          {pillars.map((pillar, i) => {
            const Icon = pillar.icon;
            return (
              <div
                key={pillar.title}
                className="group relative bg-white rounded-2xl border border-teal-100 shadow-md hover:shadow-xl hover:border-teal-300/80 p-8 flex flex-col transition-all duration-300"
                data-aos="fade-up"
                data-aos-delay={i * 120}
              >
                <div className="flex items-center justify-between gap-3 mb-6">
                  <div className="flex h-14 w-14 items-center justify-center rounded-xl bg-gradient-to-br from-teal-500 to-cyan-600 text-white shadow-lg shrink-0">
                    <Icon className="w-7 h-7" strokeWidth={2.25} />
                  </div>
                  <span
                    className="text-2xl text-teal-600/90 font-light select-none"
                    aria-hidden
                  >
                    {pillar.glyph}
                  </span>
                </div>
                <h3 className="text-xl font-bold text-gray-900 mb-3 leading-snug">
                  {pillar.title}
                </h3>
                <p className="text-gray-600 text-[15px] leading-relaxed flex-1">
                  {pillar.description}
                </p>
                <div className="mt-6 h-0.5 w-0 group-hover:w-full bg-gradient-to-r from-teal-400 to-cyan-400 rounded-full transition-all duration-500" />
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
