"use client";

import { Check, Clock, Shield } from "lucide-react";

const pillars = [
  {
    icon: Check,
    title: "Zero Manual Documentation",
    description:
      "No handwritten or manually typed compliance records — every GMP document generated by AI in real time.",
  },
  {
    icon: Clock,
    title: "Zero Compliance Gaps",
    description:
      "Every record validated against live regulatory guidelines before reaching the officer. No exceptions.",
  },
  {
    icon: Shield,
    title: "24/7 Audit Readiness",
    description:
      "Always inspection-ready — AI audit agent monitors plant operations round the clock.",
  },
];

export default function VisionPillars() {
  return (
    <section id="pillars" className="relative section-dark py-28 px-4 overflow-hidden">
      <div className="glow-orb w-[600px] h-[200px] top-0 left-1/2 -translate-x-1/2 bg-cyan-500/10" />

      <div className="relative max-w-7xl mx-auto z-10">
        <div className="text-center mb-16" data-aos="fade-up">
          <p className="label-caps mb-4">How we deliver the vision</p>
          <h2 className="heading-lg">Three pillars</h2>
        </div>

        <div className="grid md:grid-cols-3 gap-6 lg:gap-8">
          {pillars.map((pillar, i) => {
            const Icon = pillar.icon;
            return (
              <div
                key={pillar.title}
                className="card-dark p-8 flex flex-col group"
                data-aos="fade-up"
                data-aos-delay={i * 120}
              >
                <div className="flex h-12 w-12 items-center justify-center rounded-xl border border-cyan-500/20 bg-cyan-500/10 text-cyan-400 mb-6">
                  <Icon className="w-6 h-6" strokeWidth={1.75} />
                </div>
                <h3 className="text-xl font-semibold text-white mb-3 leading-snug">
                  {pillar.title}
                </h3>
                <p className="text-body text-sm flex-1">{pillar.description}</p>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
